export const GOJUON = [
  { kana: "ア", rom: "a" },
  { kana: "イ", rom: "i" },
  { kana: "ウ", rom: "u" },
  { kana: "エ", rom: "e" },
  { kana: "オ", rom: "o" },
  { kana: "カ", rom: "ka" },
  { kana: "キ", rom: "ki" },
  { kana: "ク", rom: "ku" },
  { kana: "ケ", rom: "ke" },
  { kana: "コ", rom: "ko" },
  { kana: "サ", rom: "sa" },
  { kana: "シ", rom: "shi" },
  { kana: "ス", rom: "su" },
  { kana: "セ", rom: "se" },
  { kana: "ソ", rom: "so" },
  { kana: "タ", rom: "ta" },
  { kana: "チ", rom: "chi" },
  { kana: "ツ", rom: "tsu" },
  { kana: "テ", rom: "te" },
  { kana: "ト", rom: "to" },
  { kana: "ナ", rom: "na" },
  { kana: "ニ", rom: "ni" },
  { kana: "ヌ", rom: "nu" },
  { kana: "ネ", rom: "ne" },
  { kana: "ノ", rom: "no" },
  { kana: "ハ", rom: "ha" },
  { kana: "ヒ", rom: "hi" },
  { kana: "フ", rom: "fu" },
  { kana: "ヘ", rom: "he" },
  { kana: "ホ", rom: "ho" },
  { kana: "マ", rom: "ma" },
  { kana: "ミ", rom: "mi" },
  { kana: "ム", rom: "mu" },
  { kana: "メ", rom: "me" },
  { kana: "モ", rom: "mo" },
  { kana: "ヤ", rom: "ya" },
  { kana: "", rom: "" },
  { kana: "ユ", rom: "yu" },
  { kana: "", rom: "" },
  { kana: "ヨ", rom: "yo" },
  { kana: "ラ", rom: "ra" },
  { kana: "リ", rom: "ri" },
  { kana: "ル", rom: "ru" },
  { kana: "レ", rom: "re" },
  { kana: "ロ", rom: "ro" },
  { kana: "ワ", rom: "wa" },
  { kana: "", rom: "" },
  { kana: "", rom: "" },
  { kana: "", rom: "" },
  { kana: "ヲ", rom: "wo" },
  { kana: "ン", rom: "n" },
  { kana: "", rom: "" },
  { kana: "", rom: "" },
  { kana: "", rom: "" },
  { kana: "", rom: "" },
];

export const SOKUON = [];

export const DAKUON = [
  { kana: "ガ", rom: "ga" },
  { kana: "ギ", rom: "gi" },
  { kana: "グ", rom: "gu" },
  { kana: "ゲ", rom: "ge" },
  { kana: "ゴ", rom: "go" },
  { kana: "ザ", rom: "za" },
  { kana: "ジ", rom: "ji" },
  { kana: "ズ", rom: "zu" },
  { kana: "ゼ", rom: "ze" },
  { kana: "ゾ", rom: "zo" },
  { kana: "ダ", rom: "da" },
  { kana: "ヂ", rom: "di" },
  { kana: "ヅ", rom: "du" },
  { kana: "デ", rom: "de" },
  { kana: "ド", rom: "do" },
  { kana: "バ", rom: "ba" },
  { kana: "ビ", rom: "bi" },
  { kana: "ブ", rom: "bu" },
  { kana: "ベ", rom: "be" },
  { kana: "ボ", rom: "bo" },
  { kana: "パ", rom: "pa" },
  { kana: "ピ", rom: "pi" },
  { kana: "プ", rom: "pu" },
  { kana: "ペ", rom: "pe" },
  { kana: "ポ", rom: "po" },
];

export const YOUON = [
  { kana: "キャ", rom: "kya" },
  { kana: "キュ", rom: "kyu" },
  { kana: "キョ", rom: "kyo" },
  { kana: "シャ", rom: "sha" },
  { kana: "シュ", rom: "shu" },
  { kana: "ショ", rom: "sho" },
  { kana: "チャ", rom: "cha" },
  { kana: "チュ", rom: "chu" },
  { kana: "チョ", rom: "cho" },
  { kana: "ニャ", rom: "nya" },
  { kana: "ニュ", rom: "nyu" },
  { kana: "ニョ", rom: "nyo" },
  { kana: "ヒャ", rom: "hya" },
  { kana: "ヒュ", rom: "hyu" },
  { kana: "ヒョ", rom: "hyo" },
  { kana: "ミャ", rom: "mya" },
  { kana: "ミュ", rom: "myu" },
  { kana: "ミョ", rom: "myo" },
  { kana: "リャ", rom: "rya" },
  { kana: "リュ", rom: "ryu" },
  { kana: "リョ", rom: "ryo" },
  { kana: "ギャ", rom: "gya" },
  { kana: "ギュ", rom: "gyu" },
  { kana: "ギョ", rom: "gyo" },
  { kana: "ジャ", rom: "ja" },
  { kana: "ジュ", rom: "ju" },
  { kana: "ジョ", rom: "jo" },
  { kana: "ビャ", rom: "bya" },
  { kana: "ビュ", rom: "byu" },
  { kana: "ビョ", rom: "byo" },
  { kana: "ピャ", rom: "pya" },
  { kana: "ピュ", rom: "pyu" },
  { kana: "ピョ", rom: "pyo" },
];

export const PALETTE = [
  { bg: "#FCEEF1", border: "#F4C0D1", letter: "#993556" },
  { bg: "#FBEAF0", border: "#ED93B1", letter: "#72243E" },
  { bg: "#FDEDF0", border: "#F0A0B0", letter: "#8B1A35" },
  { bg: "#FDF0F3", border: "#F2B8C6", letter: "#A0294A" },
  { bg: "#FCE8EE", border: "#E8789A", letter: "#6B1830" },
];