export const GOJUON = [
  { kana: "あ", rom: "a" },
  { kana: "い", rom: "i" },
  { kana: "う", rom: "u" },
  { kana: "え", rom: "e" },
  { kana: "お", rom: "o" },
  { kana: "か", rom: "ka" },
  { kana: "き", rom: "ki" },
  { kana: "く", rom: "ku" },
  { kana: "け", rom: "ke" },
  { kana: "こ", rom: "ko" },
  { kana: "さ", rom: "sa" },
  { kana: "し", rom: "shi" },
  { kana: "す", rom: "su" },
  { kana: "せ", rom: "se" },
  { kana: "そ", rom: "so" },
  { kana: "た", rom: "ta" },
  { kana: "ち", rom: "chi" },
  { kana: "つ", rom: "tsu" },
  { kana: "て", rom: "te" },
  { kana: "と", rom: "to" },
  { kana: "な", rom: "na" },
  { kana: "に", rom: "ni" },
  { kana: "ぬ", rom: "nu" },
  { kana: "ね", rom: "ne" },
  { kana: "の", rom: "no" },
  { kana: "は", rom: "ha" },
  { kana: "ひ", rom: "hi" },
  { kana: "ふ", rom: "fu" },
  { kana: "へ", rom: "he" },
  { kana: "ほ", rom: "ho" },
  { kana: "ま", rom: "ma" },
  { kana: "み", rom: "mi" },
  { kana: "む", rom: "mu" },
  { kana: "め", rom: "me" },
  { kana: "も", rom: "mo" },
  { kana: "や", rom: "ya" },
  { kana: "", rom: "" },
  { kana: "ゆ", rom: "yu" },
  { kana: "", rom: "" },
  { kana: "よ", rom: "yo" },
  { kana: "ら", rom: "ra" },
  { kana: "り", rom: "ri" },
  { kana: "る", rom: "ru" },
  { kana: "れ", rom: "re" },
  { kana: "ろ", rom: "ro" },
  { kana: "わ", rom: "wa" },
  { kana: "", rom: "" },
  { kana: "", rom: "" },
  { kana: "", rom: "" },
  { kana: "を", rom: "wo" },
  { kana: "ん", rom: "n" },
  { kana: "", rom: "" },
  { kana: "", rom: "" },
  { kana: "", rom: "" },
  { kana: "", rom: "" },
];

export const SOKUON = [
  { word: "きって", rom: "ki-tt-e", meaning: "sello" },
  { word: "ざっし", rom: "za-ss-hi", meaning: "revista" },
  { word: "いった", rom: "i-tt-a", meaning: "fue / dijo" },
  { word: "さっか", rom: "sa-kk-a", meaning: "autor" },
];

export const DAKUON = [
  { kana: "が", rom: "ga" },
  { kana: "ぎ", rom: "gi" },
  { kana: "ぐ", rom: "gu" },
  { kana: "げ", rom: "ge" },
  { kana: "ご", rom: "go" },
  { kana: "ざ", rom: "za" },
  { kana: "じ", rom: "ji" },
  { kana: "ず", rom: "zu" },
  { kana: "ぜ", rom: "ze" },
  { kana: "ぞ", rom: "zo" },
  { kana: "だ", rom: "da" },
  { kana: "ぢ", rom: "di" },
  { kana: "づ", rom: "du" },
  { kana: "で", rom: "de" },
  { kana: "ど", rom: "do" },
  { kana: "ば", rom: "ba" },
  { kana: "び", rom: "bi" },
  { kana: "ぶ", rom: "bu" },
  { kana: "べ", rom: "be" },
  { kana: "ぼ", rom: "bo" },
  { kana: "ぱ", rom: "pa" },
  { kana: "ぴ", rom: "pi" },
  { kana: "ぷ", rom: "pu" },
  { kana: "ぺ", rom: "pe" },
  { kana: "ぽ", rom: "po" },
];

export const YOUON = [
  { kana: "きゃ", rom: "kya" },
  { kana: "きゅ", rom: "kyu" },
  { kana: "きょ", rom: "kyo" },
  { kana: "しゃ", rom: "sha" },
  { kana: "しゅ", rom: "shu" },
  { kana: "しょ", rom: "sho" },
  { kana: "ちゃ", rom: "cha" },
  { kana: "ちゅ", rom: "chu" },
  { kana: "ちょ", rom: "cho" },
  { kana: "にゃ", rom: "nya" },
  { kana: "にゅ", rom: "nyu" },
  { kana: "にょ", rom: "nyo" },
  { kana: "ひゃ", rom: "hya" },
  { kana: "ひゅ", rom: "hyu" },
  { kana: "ひょ", rom: "hyo" },
  { kana: "みゃ", rom: "mya" },
  { kana: "みゅ", rom: "myu" },
  { kana: "みょ", rom: "myo" },
  { kana: "りゃ", rom: "rya" },
  { kana: "りゅ", rom: "ryu" },
  { kana: "りょ", rom: "ryo" },
  { kana: "ぎゃ", rom: "gya" },
  { kana: "ぎゅ", rom: "gyu" },
  { kana: "ぎょ", rom: "gyo" },
  { kana: "じゃ", rom: "ja" },
  { kana: "じゅ", rom: "ju" },
  { kana: "じょ", rom: "jo" },
  { kana: "びゃ", rom: "bya" },
  { kana: "びゅ", rom: "byu" },
  { kana: "びょ", rom: "byo" },
  { kana: "ぴゃ", rom: "pya" },
  { kana: "ぴゅ", rom: "pyu" },
  { kana: "ぴょ", rom: "pyo" },
];

export const PALETTE = [
  { bg: "#FCEEF1", border: "#F4C0D1", letter: "#993556" },
  { bg: "#FBEAF0", border: "#ED93B1", letter: "#72243E" },
  { bg: "#FDEDF0", border: "#F0A0B0", letter: "#8B1A35" },
  { bg: "#FDF0F3", border: "#F2B8C6", letter: "#A0294A" },
  { bg: "#FCE8EE", border: "#E8789A", letter: "#6B1830" },
];