export const GOJUON = [
  { kana: "あ", rom: "a", sound: require("../assets/audio/hiragana/a.mp3") },
  { kana: "い", rom: "i", sound: require("../assets/audio/hiragana/i.mp3") },
  { kana: "う", rom: "u", sound: require("../assets/audio/hiragana/u.mp3") },
  { kana: "え", rom: "e", sound: require("../assets/audio/hiragana/e.mp3") },
  { kana: "お", rom: "o", sound: require("../assets/audio/hiragana/o.mp3") },
  { kana: "か", rom: "ka", sound: require("../assets/audio/hiragana/ka.mp3") },
  { kana: "き", rom: "ki", sound: require("../assets/audio/hiragana/ki.mp3") },
  { kana: "く", rom: "ku", sound: require("../assets/audio/hiragana/ku.mp3") },
  { kana: "け", rom: "ke", sound: require("../assets/audio/hiragana/ke.mp3") },
  { kana: "こ", rom: "ko", sound: require("../assets/audio/hiragana/ko.mp3") },
  { kana: "さ", rom: "sa", sound: require("../assets/audio/hiragana/sa.mp3") },
  { kana: "し", rom: "shi", sound: require("../assets/audio/hiragana/shi.mp3") },
  { kana: "す", rom: "su", sound: require("../assets/audio/hiragana/su.mp3") },
  { kana: "せ", rom: "se", sound: require("../assets/audio/hiragana/se.mp3") },
  { kana: "そ", rom: "so", sound: require("../assets/audio/hiragana/so.mp3") },
  { kana: "た", rom: "ta", sound: require("../assets/audio/hiragana/ta.mp3") },
  { kana: "ち", rom: "chi", sound: require("../assets/audio/hiragana/chi.mp3") },
  { kana: "つ", rom: "tsu", sound: require("../assets/audio/hiragana/tsu.mp3") },
  { kana: "て", rom: "te", sound: require("../assets/audio/hiragana/te.mp3") },
  { kana: "と", rom: "to", sound: require("../assets/audio/hiragana/to.mp3") },
  { kana: "な", rom: "na", sound: require("../assets/audio/hiragana/na.mp3") },
  { kana: "に", rom: "ni", sound: require("../assets/audio/hiragana/ni.mp3") },
  { kana: "ぬ", rom: "nu", sound: require("../assets/audio/hiragana/nu.mp3") },
  { kana: "ね", rom: "ne", sound: require("../assets/audio/hiragana/ne.mp3") },
  { kana: "の", rom: "no", sound: require("../assets/audio/hiragana/no.mp3") },
  { kana: "は", rom: "ha", sound: require("../assets/audio/hiragana/ha.mp3") },
  { kana: "ひ", rom: "hi", sound: require("../assets/audio/hiragana/hi.mp3") },
  { kana: "ふ", rom: "fu", sound: require("../assets/audio/hiragana/fu.mp3") },
  { kana: "へ", rom: "he", sound: require("../assets/audio/hiragana/he.mp3") },
  { kana: "ほ", rom: "ho", sound: require("../assets/audio/hiragana/ho.mp3") },
  { kana: "ま", rom: "ma", sound: require("../assets/audio/hiragana/ma.mp3") },
  { kana: "み", rom: "mi", sound: require("../assets/audio/hiragana/mi.mp3") },
  { kana: "む", rom: "mu", sound: require("../assets/audio/hiragana/mu.mp3") },
  { kana: "め", rom: "me", sound: require("../assets/audio/hiragana/me.mp3") },
  { kana: "も", rom: "mo", sound: require("../assets/audio/hiragana/mo.mp3") },
  { kana: "や", rom: "ya", sound: require("../assets/audio/hiragana/ya.mp3") },
  { kana: "", rom: "", sound: null },
  { kana: "ゆ", rom: "yu", sound: require("../assets/audio/hiragana/yu.mp3") },
  { kana: "", rom: "", sound: null },
  { kana: "よ", rom: "yo", sound: require("../assets/audio/hiragana/yo.mp3") },
  { kana: "ら", rom: "ra", sound: require("../assets/audio/hiragana/ra.mp3") },
  { kana: "り", rom: "ri", sound: require("../assets/audio/hiragana/ri.mp3") },
  { kana: "る", rom: "ru", sound: require("../assets/audio/hiragana/ru.mp3") },
  { kana: "れ", rom: "re", sound: require("../assets/audio/hiragana/re.mp3") },
  { kana: "ろ", rom: "ro", sound: require("../assets/audio/hiragana/ro.mp3") },
  { kana: "わ", rom: "wa", sound: require("../assets/audio/hiragana/wa.mp3") },
  { kana: "", rom: "", sound: null },
  { kana: "", rom: "", sound: null },
  { kana: "", rom: "", sound: null },
  { kana: "を", rom: "wo", sound: require("../assets/audio/hiragana/wo.mp3") },
  { kana: "ん", rom: "n", sound: require("../assets/audio/hiragana/n.mp3") },
  { kana: "", rom: "", sound: null },
  { kana: "", rom: "", sound: null },
  { kana: "", rom: "", sound: null },
  { kana: "", rom: "", sound: null },
];

export const SOKUON = [
  { word: "きって", rom: "ki-tt-e", meaning: "sello", sound: require("../assets/audio/hiragana/kitte.mp3") },
  { word: "ざっし", rom: "za-ss-hi", meaning: "revista", sound: require("../assets/audio/hiragana/zasshi.mp3") },
  { word: "いった", rom: "i-tt-a", meaning: "fue / dijo", sound: require("../assets/audio/hiragana/itta.mp3") },
  { word: "さっか", rom: "sa-kk-a", meaning: "autor", sound: require("../assets/audio/hiragana/sakka.mp3") },
];

export const DAKUON = [
  { kana: "が", rom: "ga", sound: require("../assets/audio/hiragana/ga.mp3") },
  { kana: "ぎ", rom: "gi", sound: require("../assets/audio/hiragana/gi.mp3") },
  { kana: "ぐ", rom: "gu", sound: require("../assets/audio/hiragana/gu.mp3") },
  { kana: "げ", rom: "ge", sound: require("../assets/audio/hiragana/ge.mp3") },
  { kana: "ご", rom: "go", sound: require("../assets/audio/hiragana/go.mp3") },
  { kana: "ざ", rom: "za", sound: require("../assets/audio/hiragana/za.mp3") },
  { kana: "じ", rom: "ji", sound: require("../assets/audio/hiragana/ji.mp3") },
  { kana: "ず", rom: "zu", sound: require("../assets/audio/hiragana/zu.mp3") },
  { kana: "ぜ", rom: "ze", sound: require("../assets/audio/hiragana/ze.mp3") },
  { kana: "ぞ", rom: "zo", sound: require("../assets/audio/hiragana/zo.mp3") },
  { kana: "だ", rom: "da", sound: require("../assets/audio/hiragana/da.mp3") },
  { kana: "ぢ", rom: "di", sound: require("../assets/audio/hiragana/di.mp3") },
  { kana: "づ", rom: "du", sound: require("../assets/audio/hiragana/du.mp3") },
  { kana: "で", rom: "de", sound: require("../assets/audio/hiragana/de.mp3") },
  { kana: "ど", rom: "do", sound: require("../assets/audio/hiragana/do.mp3") },
  { kana: "ば", rom: "ba", sound: require("../assets/audio/hiragana/ba.mp3") },
  { kana: "び", rom: "bi", sound: require("../assets/audio/hiragana/bi.mp3") },
  { kana: "ぶ", rom: "bu", sound: require("../assets/audio/hiragana/bu.mp3") },
  { kana: "べ", rom: "be", sound: require("../assets/audio/hiragana/be.mp3") },
  { kana: "ぼ", rom: "bo", sound: require("../assets/audio/hiragana/bo.mp3") },
  { kana: "ぱ", rom: "pa", sound: require("../assets/audio/hiragana/pa.mp3") },
  { kana: "ぴ", rom: "pi", sound: require("../assets/audio/hiragana/pi.mp3") },
  { kana: "ぷ", rom: "pu", sound: require("../assets/audio/hiragana/pu.mp3") },
  { kana: "ぺ", rom: "pe", sound: require("../assets/audio/hiragana/pe.mp3") },
  { kana: "ぽ", rom: "po", sound: require("../assets/audio/hiragana/po.mp3") },
];

export const YOUON = [
  { kana: "きゃ", rom: "kya", sound: require("../assets/audio/hiragana/kya.mp3") },
  { kana: "きゅ", rom: "kyu", sound: require("../assets/audio/hiragana/kyu.mp3") },
  { kana: "きょ", rom: "kyo", sound: require("../assets/audio/hiragana/kyo.mp3") },
  { kana: "しゃ", rom: "sha", sound: require("../assets/audio/hiragana/sha.mp3") },
  { kana: "しゅ", rom: "shu", sound: require("../assets/audio/hiragana/shu.mp3") },
  { kana: "しょ", rom: "sho", sound: require("../assets/audio/hiragana/sho.mp3") },
  { kana: "ちゃ", rom: "cha", sound: require("../assets/audio/hiragana/cha.mp3") },
  { kana: "ちゅ", rom: "chu", sound: require("../assets/audio/hiragana/chu.mp3") },
  { kana: "ちょ", rom: "cho", sound: require("../assets/audio/hiragana/cho.mp3") },
  { kana: "にゃ", rom: "nya", sound: require("../assets/audio/hiragana/nya.mp3") },
  { kana: "にゅ", rom: "nyu", sound: require("../assets/audio/hiragana/nyu.mp3") },
  { kana: "にょ", rom: "nyo", sound: require("../assets/audio/hiragana/nyo.mp3") },
  { kana: "ひゃ", rom: "hya", sound: require("../assets/audio/hiragana/hya.mp3") },
  { kana: "ひゅ", rom: "hyu", sound: require("../assets/audio/hiragana/hyu.mp3") },
  { kana: "ひょ", rom: "hyo", sound: require("../assets/audio/hiragana/hyo.mp3") },
  { kana: "みゃ", rom: "mya", sound: require("../assets/audio/hiragana/mya.mp3") },
  { kana: "みゅ", rom: "myu", sound: require("../assets/audio/hiragana/myu.mp3") },
  { kana: "みょ", rom: "myo", sound: require("../assets/audio/hiragana/myo.mp3") },
  { kana: "りゃ", rom: "rya", sound: require("../assets/audio/hiragana/rya.mp3") },
  { kana: "りゅ", rom: "ryu", sound: require("../assets/audio/hiragana/ryu.mp3") },
  { kana: "りょ", rom: "ryo", sound: require("../assets/audio/hiragana/ryo.mp3") },
  { kana: "ぎゃ", rom: "gya", sound: require("../assets/audio/hiragana/gya.mp3") },
  { kana: "ぎゅ", rom: "gyu", sound: require("../assets/audio/hiragana/gyu.mp3") },
  { kana: "ぎょ", rom: "gyo", sound: require("../assets/audio/hiragana/gyo.mp3") },
  { kana: "じゃ", rom: "ja", sound: require("../assets/audio/hiragana/ja.mp3") },
  { kana: "じゅ", rom: "ju", sound: require("../assets/audio/hiragana/ju.mp3") },
  { kana: "じょ", rom: "jo", sound: require("../assets/audio/hiragana/jo.mp3") },
  { kana: "びゃ", rom: "bya", sound: require("../assets/audio/hiragana/bya.mp3") },
  { kana: "びゅ", rom: "byu", sound: require("../assets/audio/hiragana/byu.mp3") },
  { kana: "びょ", rom: "byo", sound: require("../assets/audio/hiragana/byo.mp3") },
  { kana: "ぴゃ", rom: "pya", sound: require("../assets/audio/hiragana/pya.mp3") },
  { kana: "ぴゅ", rom: "pyu", sound: require("../assets/audio/hiragana/pyu.mp3") },
  { kana: "ぴょ", rom: "pyo", sound: require("../assets/audio/hiragana/pyo.mp3") },
];

export const PALETTE = [
  { bg: "#FCEEF1", border: "#F4C0D1", letter: "#993556" },
  { bg: "#FBEAF0", border: "#ED93B1", letter: "#72243E" },
  { bg: "#FDEDF0", border: "#F0A0B0", letter: "#8B1A35" },
  { bg: "#FDF0F3", border: "#F2B8C6", letter: "#A0294A" },
  { bg: "#FCE8EE", border: "#E8789A", letter: "#6B1830" },
];