export const ALPHABET = [
  { letter: "A", pronunciation: "ei" },
  { letter: "B", pronunciation: "bi" },
  { letter: "C", pronunciation: "si" },
  { letter: "D", pronunciation: "di" },
  { letter: "E", pronunciation: "i" },
  { letter: "F", pronunciation: "ef" },
  { letter: "G", pronunciation: "yi" },
  { letter: "H", pronunciation: "eich" },
  { letter: "I", pronunciation: "ai" },
  { letter: "J", pronunciation: "yei" },
  { letter: "K", pronunciation: "kei" },
  { letter: "L", pronunciation: "el" },
  { letter: "M", pronunciation: "em" },
  { letter: "N", pronunciation: "en" },
  { letter: "O", pronunciation: "ou" },
  { letter: "P", pronunciation: "pi" },
  { letter: "Q", pronunciation: "kiu" },
  { letter: "R", pronunciation: "ar" },
  { letter: "S", pronunciation: "es" },
  { letter: "T", pronunciation: "ti" },
  { letter: "U", pronunciation: "iu" },
  { letter: "V", pronunciation: "vi" },
  { letter: "W", pronunciation: "dabliu" },
  { letter: "X", pronunciation: "eks" },
  { letter: "Y", pronunciation: "wai" },
  { letter: "Z", pronunciation: "zi" },
];

export const CARD_COLORS = [
  { bg: "#EAF4FF", border: "#85B7EB", letter: "#185FA5", badge: "#B5D4F4", badgeText: "#0C447C" },
  { bg: "#EEF0FD", border: "#A9B4F0", letter: "#2D3FAA", badge: "#CDD3F7", badgeText: "#1E2D88" },
  { bg: "#E8F6FB", border: "#7DCCE8", letter: "#0D6B8A", badge: "#B0E2F2", badgeText: "#085570" },
  { bg: "#EDF2F8", border: "#93AFD4", letter: "#2A4F7C", badge: "#BCCFE8", badgeText: "#1C3A60" },
  { bg: "#EEEFFE", border: "#AAADF5", letter: "#3035B8", badge: "#D0D2FB", badgeText: "#212590" },
  { bg: "#EDF3F7", border: "#8FAEC8", letter: "#2B4E6E", badge: "#BDD0DF", badgeText: "#1C3C55" },
];