export const GOJUON = [
  { kana: "ア", rom: "a", sound: require("../assets/audio/katakana/a.mp3") },
  { kana: "イ", rom: "i", sound: require("../assets/audio/katakana/i.mp3") },
  { kana: "ウ", rom: "u", sound: require("../assets/audio/katakana/u.mp3") },
  { kana: "エ", rom: "e", sound: require("../assets/audio/katakana/e.mp3") },
  { kana: "オ", rom: "o", sound: require("../assets/audio/katakana/o.mp3") },
  { kana: "カ", rom: "ka", sound: require("../assets/audio/katakana/ka.mp3") },
  { kana: "キ", rom: "ki", sound: require("../assets/audio/katakana/ki.mp3") },
  { kana: "ク", rom: "ku", sound: require("../assets/audio/katakana/ku.mp3") },
  { kana: "ケ", rom: "ke", sound: require("../assets/audio/katakana/ke.mp3") },
  { kana: "コ", rom: "ko", sound: require("../assets/audio/katakana/ko.mp3") },
  { kana: "サ", rom: "sa", sound: require("../assets/audio/katakana/sa.mp3") },
  { kana: "シ", rom: "shi", sound: require("../assets/audio/katakana/shi.mp3") },
  { kana: "ス", rom: "su", sound: require("../assets/audio/katakana/su.mp3") },
  { kana: "セ", rom: "se", sound: require("../assets/audio/katakana/se.mp3") },
  { kana: "ソ", rom: "so", sound: require("../assets/audio/katakana/so.mp3") },
  { kana: "タ", rom: "ta", sound: require("../assets/audio/katakana/ta.mp3") },
  { kana: "チ", rom: "chi", sound: require("../assets/audio/katakana/chi.mp3") },
  { kana: "ツ", rom: "tsu", sound: require("../assets/audio/katakana/tsu.mp3") },
  { kana: "テ", rom: "te", sound: require("../assets/audio/katakana/te.mp3") },
  { kana: "ト", rom: "to", sound: require("../assets/audio/katakana/to.mp3") },
  { kana: "ナ", rom: "na", sound: require("../assets/audio/katakana/na.mp3") },
  { kana: "ニ", rom: "ni", sound: require("../assets/audio/katakana/ni.mp3") },
  { kana: "ヌ", rom: "nu", sound: require("../assets/audio/katakana/nu.mp3") },
  { kana: "ネ", rom: "ne", sound: require("../assets/audio/katakana/ne.mp3") },
  { kana: "ノ", rom: "no", sound: require("../assets/audio/katakana/no.mp3") },
  { kana: "ハ", rom: "ha", sound: require("../assets/audio/katakana/ha.mp3") },
  { kana: "ヒ", rom: "hi", sound: require("../assets/audio/katakana/hi.mp3") },
  { kana: "フ", rom: "fu", sound: require("../assets/audio/katakana/fu.mp3") },
  { kana: "ヘ", rom: "he", sound: require("../assets/audio/katakana/he.mp3") },
  { kana: "ホ", rom: "ho", sound: require("../assets/audio/katakana/ho.mp3") },
  { kana: "マ", rom: "ma", sound: require("../assets/audio/katakana/ma.mp3") },
  { kana: "ミ", rom: "mi", sound: require("../assets/audio/katakana/mi.mp3") },
  { kana: "ム", rom: "mu", sound: require("../assets/audio/katakana/mu.mp3") },
  { kana: "メ", rom: "me", sound: require("../assets/audio/katakana/me.mp3") },
  { kana: "モ", rom: "mo", sound: require("../assets/audio/katakana/mo.mp3") },
  { kana: "ヤ", rom: "ya", sound: require("../assets/audio/katakana/ya.mp3") },
  { kana: "", rom: "", sound: null },
  { kana: "ユ", rom: "yu", sound: require("../assets/audio/katakana/yu.mp3") },
  { kana: "", rom: "", sound: null },
  { kana: "ヨ", rom: "yo", sound: require("../assets/audio/katakana/yo.mp3") },
  { kana: "ラ", rom: "ra", sound: require("../assets/audio/katakana/ra.mp3") },
  { kana: "リ", rom: "ri", sound: require("../assets/audio/katakana/ri.mp3") },
  { kana: "ル", rom: "ru", sound: require("../assets/audio/katakana/ru.mp3") },
  { kana: "レ", rom: "re", sound: require("../assets/audio/katakana/re.mp3") },
  { kana: "ロ", rom: "ro", sound: require("../assets/audio/katakana/ro.mp3") },
  { kana: "ワ", rom: "wa", sound: require("../assets/audio/katakana/wa.mp3") },
  { kana: "", rom: "", sound: null },
  { kana: "", rom: "", sound: null },
  { kana: "", rom: "", sound: null },
  { kana: "ヲ", rom: "wo", sound: require("../assets/audio/katakana/wo.mp3") },
  { kana: "ン", rom: "n", sound: require("../assets/audio/katakana/n.mp3") },
  { kana: "", rom: "", sound: null },
  { kana: "", rom: "", sound: null },
  { kana: "", rom: "", sound: null },
  { kana: "", rom: "", sound: null },
];

export const SOKUON = [
  { word: "コップ", rom: "ko-pp-u", meaning: "vaso", sound: require("../assets/audio/katakana/ko-pp-u.mp3") },
  { word: "ベッド", rom: "be-dd-o", meaning: "cama", sound: require("../assets/audio/katakana/be-dd-o.mp3") },
  { word: "チケット", rom: "chi-ke-tt-o", meaning: "boleto", sound: require("../assets/audio/katakana/chi-ke-tt-o.mp3") },
  { word: "マッチ", rom: "ma-cc-hi", meaning: "fósforo", sound: require("../assets/audio/katakana/ma-cc-hi.mp3") },
  { word: "サッカー", rom: "sa-kk-a-", meaning: "fútbol", sound: require("../assets/audio/katakana/sa-kk-a-.mp3") },
  { word: "カセット", rom: "ka-se-tt-o", meaning: "cassette", sound: require("../assets/audio/katakana/ka-se-tt-o.mp3") },
];

export const DAKUON = [
  { kana: "ガ", rom: "ga", sound: require("../assets/audio/katakana/ga.mp3") },
  { kana: "ギ", rom: "gi", sound: require("../assets/audio/katakana/gi.mp3") },
  { kana: "グ", rom: "gu", sound: require("../assets/audio/katakana/gu.mp3") },
  { kana: "ゲ", rom: "ge", sound: require("../assets/audio/katakana/ge.mp3") },
  { kana: "ゴ", rom: "go", sound: require("../assets/audio/katakana/go.mp3") },
  { kana: "ザ", rom: "za", sound: require("../assets/audio/katakana/za.mp3") },
  { kana: "ジ", rom: "ji", sound: require("../assets/audio/katakana/ji.mp3") },
  { kana: "ズ", rom: "zu", sound: require("../assets/audio/katakana/zu.mp3") },
  { kana: "ゼ", rom: "ze", sound: require("../assets/audio/katakana/ze.mp3") },
  { kana: "ゾ", rom: "zo", sound: require("../assets/audio/katakana/zo.mp3") },
  { kana: "ダ", rom: "da", sound: require("../assets/audio/katakana/da.mp3") },
  { kana: "ヂ", rom: "di", sound: require("../assets/audio/katakana/di.mp3") },
  { kana: "ヅ", rom: "du", sound: require("../assets/audio/katakana/du.mp3") },
  { kana: "デ", rom: "de", sound: require("../assets/audio/katakana/de.mp3") },
  { kana: "ド", rom: "do", sound: require("../assets/audio/katakana/do.mp3") },
  { kana: "バ", rom: "ba", sound: require("../assets/audio/katakana/ba.mp3") },
  { kana: "ビ", rom: "bi", sound: require("../assets/audio/katakana/bi.mp3") },
  { kana: "ブ", rom: "bu", sound: require("../assets/audio/katakana/bu.mp3") },
  { kana: "ベ", rom: "be", sound: require("../assets/audio/katakana/be.mp3") },
  { kana: "ボ", rom: "bo", sound: require("../assets/audio/katakana/bo.mp3") },
  { kana: "パ", rom: "pa", sound: require("../assets/audio/katakana/pa.mp3") },
  { kana: "ピ", rom: "pi", sound: require("../assets/audio/katakana/pi.mp3") },
  { kana: "プ", rom: "pu", sound: require("../assets/audio/katakana/pu.mp3") },
  { kana: "ペ", rom: "pe", sound: require("../assets/audio/katakana/pe.mp3") },
  { kana: "ポ", rom: "po", sound: require("../assets/audio/katakana/po.mp3") },
];

export const YOUON = [
  { kana: "キャ", rom: "kya", sound: require("../assets/audio/katakana/kya.mp3") },
  { kana: "キュ", rom: "kyu", sound: require("../assets/audio/katakana/kyu.mp3") },
  { kana: "キョ", rom: "kyo", sound: require("../assets/audio/katakana/kyo.mp3") },
  { kana: "シャ", rom: "sha", sound: require("../assets/audio/katakana/sha.mp3") },
  { kana: "シュ", rom: "shu", sound: require("../assets/audio/katakana/shu.mp3") },
  { kana: "ショ", rom: "sho", sound: require("../assets/audio/katakana/sho.mp3") },
  { kana: "チャ", rom: "cha", sound: require("../assets/audio/katakana/cha.mp3") },
  { kana: "チュ", rom: "chu", sound: require("../assets/audio/katakana/chu.mp3") },
  { kana: "チョ", rom: "cho", sound: require("../assets/audio/katakana/cho.mp3") },
  { kana: "ニャ", rom: "nya", sound: require("../assets/audio/katakana/nya.mp3") },
  { kana: "ニュ", rom: "nyu", sound: require("../assets/audio/katakana/nyu.mp3") },
  { kana: "ニョ", rom: "nyo", sound: require("../assets/audio/katakana/nyo.mp3") },
  { kana: "ヒャ", rom: "hya", sound: require("../assets/audio/katakana/hya.mp3") },
  { kana: "ヒュ", rom: "hyu", sound: require("../assets/audio/katakana/hyu.mp3") },
  { kana: "ヒョ", rom: "hyo", sound: require("../assets/audio/katakana/hyo.mp3") },
  { kana: "ミャ", rom: "mya", sound: require("../assets/audio/katakana/mya.mp3") },
  { kana: "ミュ", rom: "myu", sound: require("../assets/audio/katakana/myu.mp3") },
  { kana: "ミョ", rom: "myo", sound: require("../assets/audio/katakana/myo.mp3") },
  { kana: "リャ", rom: "rya", sound: require("../assets/audio/katakana/rya.mp3") },
  { kana: "リュ", rom: "ryu", sound: require("../assets/audio/katakana/ryu.mp3") },
  { kana: "リョ", rom: "ryo", sound: require("../assets/audio/katakana/ryo.mp3") },
  { kana: "ギャ", rom: "gya", sound: require("../assets/audio/katakana/gya.mp3") },
  { kana: "ギュ", rom: "gyu", sound: require("../assets/audio/katakana/gyu.mp3") },
  { kana: "ギョ", rom: "gyo", sound: require("../assets/audio/katakana/gyo.mp3") },
  { kana: "ジャ", rom: "ja", sound: require("../assets/audio/katakana/ja.mp3") },
  { kana: "ジュ", rom: "ju", sound: require("../assets/audio/katakana/ju.mp3") },
  { kana: "ジョ", rom: "jo", sound: require("../assets/audio/katakana/jo.mp3") },
  { kana: "ビャ", rom: "bya", sound: require("../assets/audio/katakana/bya.mp3") },
  { kana: "ビュ", rom: "byu", sound: require("../assets/audio/katakana/byu.mp3") },
  { kana: "ビョ", rom: "byo", sound: require("../assets/audio/katakana/byo.mp3") },
  { kana: "ピャ", rom: "pya", sound: require("../assets/audio/katakana/pya.mp3") },
  { kana: "ピュ", rom: "pyu", sound: require("../assets/audio/katakana/pyu.mp3") },
  { kana: "ピョ", rom: "pyo", sound: require("../assets/audio/katakana/pyo.mp3") },
];

export const PALETTE = [
  { bg: "#FCEEF1", border: "#F4C0D1", letter: "#993556" },
  { bg: "#FBEAF0", border: "#ED93B1", letter: "#72243E" },
  { bg: "#FDEDF0", border: "#F0A0B0", letter: "#8B1A35" },
  { bg: "#FDF0F3", border: "#F2B8C6", letter: "#A0294A" },
  { bg: "#FCE8EE", border: "#E8789A", letter: "#6B1830" },
];