export const ALPHABET = [
  { letter: "A", pronunciation: "ei", sound: require("../assets/audio/alphabetEnglish/a.mp3") },
  { letter: "B", pronunciation: "bi", sound: require("../assets/audio/alphabetEnglish/b.mp3") },
  { letter: "C", pronunciation: "si", sound: require("../assets/audio/alphabetEnglish/c.mp3") },
  { letter: "D", pronunciation: "di", sound: require("../assets/audio/alphabetEnglish/d.mp3") },
  { letter: "E", pronunciation: "i", sound: require("../assets/audio/alphabetEnglish/e.mp3") },
  { letter: "F", pronunciation: "ef", sound: require("../assets/audio/alphabetEnglish/f.mp3") },
  { letter: "G", pronunciation: "yi", sound: require("../assets/audio/alphabetEnglish/g.mp3") },
  { letter: "H", pronunciation: "eich", sound: require("../assets/audio/alphabetEnglish/h.mp3") },
  { letter: "I", pronunciation: "ai", sound: require("../assets/audio/alphabetEnglish/i.mp3") },
  { letter: "J", pronunciation: "yei", sound: require("../assets/audio/alphabetEnglish/j.mp3") },
  { letter: "K", pronunciation: "kei", sound: require("../assets/audio/alphabetEnglish/k.mp3") },
  { letter: "L", pronunciation: "el", sound: require("../assets/audio/alphabetEnglish/l.mp3") },
  { letter: "M", pronunciation: "em", sound: require("../assets/audio/alphabetEnglish/m.mp3") },
  { letter: "N", pronunciation: "en", sound: require("../assets/audio/alphabetEnglish/n.mp3") },
  { letter: "O", pronunciation: "ou", sound: require("../assets/audio/alphabetEnglish/o.mp3") },
  { letter: "P", pronunciation: "pi", sound: require("../assets/audio/alphabetEnglish/p.mp3") },
  { letter: "Q", pronunciation: "kiu", sound: require("../assets/audio/alphabetEnglish/q.mp3") },
  { letter: "R", pronunciation: "ar", sound: require("../assets/audio/alphabetEnglish/r.mp3") },
  { letter: "S", pronunciation: "es", sound: require("../assets/audio/alphabetEnglish/s.mp3") },
  { letter: "T", pronunciation: "ti", sound: require("../assets/audio/alphabetEnglish/t.mp3") },
  { letter: "U", pronunciation: "iu", sound: require("../assets/audio/alphabetEnglish/u.mp3") },
  { letter: "V", pronunciation: "vi", sound: require("../assets/audio/alphabetEnglish/v.mp3") },
  { letter: "W", pronunciation: "dabliu", sound: require("../assets/audio/alphabetEnglish/w.mp3") },
  { letter: "X", pronunciation: "eks", sound: require("../assets/audio/alphabetEnglish/x.mp3") },
  { letter: "Y", pronunciation: "wai", sound: require("../assets/audio/alphabetEnglish/y.mp3") },
  { letter: "Z", pronunciation: "zi", sound: require("../assets/audio/alphabetEnglish/z.mp3") },
];

export const CARD_COLORS = [
  { bg: "#EAF4FF", border: "#85B7EB", letter: "#185FA5", badge: "#B5D4F4", badgeText: "#0C447C" },
  { bg: "#EEF0FD", border: "#A9B4F0", letter: "#2D3FAA", badge: "#CDD3F7", badgeText: "#1E2D88" },
  { bg: "#E8F6FB", border: "#7DCCE8", letter: "#0D6B8A", badge: "#B0E2F2", badgeText: "#085570" },
  { bg: "#EDF2F8", border: "#93AFD4", letter: "#2A4F7C", badge: "#BCCFE8", badgeText: "#1C3A60" },
  { bg: "#EEEFFE", border: "#AAADF5", letter: "#3035B8", badge: "#D0D2FB", badgeText: "#212590" },
  { bg: "#EDF3F7", border: "#8FAEC8", letter: "#2B4E6E", badge: "#BDD0DF", badgeText: "#1C3C55" },
];